### ISSUE TITLE
How to simulate only 5 telescopes

### ISSUE THREAD

**Issue by seinecke** [UofA-HEAG/CTA-Simulation#8]
These 5 telescopes should be the ones in the centre of the entire array. One in the very centre and the other ones around this one in a distance of ~200m.

**Comment by seinecke** [comment]
Could we just add the following:

```
TELESCOPE  0E2   0E2     $(SSTHT)     $(SSTRAD) # Telescope 70  (SST) rc=1195.98 [3HB9]
```
Is that a comment following the ```#```? In the same input card, they are using ```//``` and ```*```  for a comment and I'm actually not quite sure about the language in this file.

**Comment by hdp1213** [comment]
Yep, that looks good to me!

The language is an interesting one. It seems to be a homebrew language particular to CORSIKA. I went digging in the manual, and found the only comment character being the asterisk. Now, this is where things get interesting. Each line starts with a keyword (like `TELESCOPE`) which takes a certain number of arguments. CORSIKA simply interprets any other arguments after this number as a comment, which is why we get this mishmash of `#` and `//` thrown around. They functionally don't do anything, but I suppose whoever was editing the file at the time either had done a lot of C++ or Python recently!

I think that about closes this issue. If you have any other comments, feel free to say, otherwise I think we're all good here.
